table bioenergy
	lineageTag: 48c56081-bdd0-4c8d-8ef9-94b5e013e5f5

	column 'Domain Code'
		dataType: string
		lineageTag: 0051296a-720c-4bae-a3ca-9cdcf5ef2e95
		summarizeBy: none
		sourceColumn: Domain Code

		annotation SummarizationSetBy = Automatic

	column Domain
		dataType: string
		lineageTag: f30286fc-95ae-4226-804f-8edd04ada7a7
		summarizeBy: none
		sourceColumn: Domain

		annotation SummarizationSetBy = Automatic

	column 'Area Code (M49)'
		dataType: string
		lineageTag: 1c0187ae-0f00-4d2a-b238-030143d62ed0
		summarizeBy: none
		sourceColumn: Area Code (M49)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: d6379fbf-e8df-4842-bc88-19cf1db09ea5
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column 'Element Code'
		dataType: int64
		formatString: 0
		lineageTag: 0ffa8677-c29a-41f9-b03e-f2053a04404e
		summarizeBy: count
		sourceColumn: Element Code

		annotation SummarizationSetBy = Automatic

	column Element
		dataType: string
		lineageTag: 10943007-3052-495d-948b-38abcde94e5f
		summarizeBy: none
		sourceColumn: Element

		annotation SummarizationSetBy = Automatic

	column 'Item Code'
		dataType: int64
		formatString: 0
		lineageTag: 276bdf42-7435-4947-90b7-9e9ce308e058
		summarizeBy: count
		sourceColumn: Item Code

		annotation SummarizationSetBy = Automatic

	column Item
		dataType: string
		lineageTag: db8b1a1c-6200-46a4-890a-0f623ad0cf29
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	column 'Year Code'
		dataType: int64
		formatString: 0
		lineageTag: 29a25a5f-d31a-42fc-a603-841728257fec
		summarizeBy: count
		sourceColumn: Year Code

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: db5ca0db-f11b-435a-a674-37db981a0cc2
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: ee712a36-b239-47c5-8d4e-8dd714cf8cd4
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 499408d2-dd5e-46d9-adfd-ccb62e615f0a
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Flag
		dataType: string
		lineageTag: 85e7f2db-7f3b-453a-b58d-8ee6c9486c92
		summarizeBy: none
		sourceColumn: Flag

		annotation SummarizationSetBy = Automatic

	column 'Flag Description'
		dataType: string
		lineageTag: 6ba315c2-da22-4009-8f27-6f7cb8bbeea0
		summarizeBy: none
		sourceColumn: Flag Description

		annotation SummarizationSetBy = Automatic

	partition bioenergy = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\emily\Documents\whats_cooking\Bioenergy\bioenergy.csv"), [Delimiter = ",", Columns = 14, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Domain Code", type text}, {"Domain", type text}, {"Area Code (M49)", Int64.Type}, {"Area", type text}, {"Element Code", Int64.Type}, {"Element", type text}, {"Item Code", Int64.Type}, {"Item", type text}, {"Year Code", Int64.Type}, {"Year", Int64.Type}, {"Unit", type text}, {"Value", type number}, {"Flag", type text}, {"Flag Description", type text}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

