table countries
	lineageTag: 2472b0ad-2e16-4c29-87f6-2a239352ea62

	column Area
		dataType: string
		lineageTag: a482e86e-4332-4a90-a346-9b6b527bebdd
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column 'Area Code (M49)'
		dataType: string
		lineageTag: 0c7ac573-85f9-49e5-921f-031349639a75
		summarizeBy: none
		sourceColumn: Area Code (M49)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'LSU Region Equivalent'
		dataType: string
		lineageTag: 70542aec-cd89-4e8b-b7c6-532aa6395d41
		summarizeBy: none
		sourceColumn: LSU Region Equivalent

		annotation SummarizationSetBy = Automatic

	column Cattle_LSU
		dataType: double
		lineageTag: bdcba341-337b-4bf7-bdad-34554345eef1
		summarizeBy: sum
		sourceColumn: Cattle_LSU

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sheep_LSU
		dataType: double
		lineageTag: 90d4c30d-32ac-4d26-be84-266fab10d227
		summarizeBy: sum
		sourceColumn: Sheep_LSU

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Goats_LSU
		dataType: double
		lineageTag: fd9ed4bd-733c-4bbd-8957-96d57142e366
		summarizeBy: sum
		sourceColumn: Goats_LSU

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Chickens_LSU
		dataType: double
		lineageTag: f845f5bc-72d6-42ce-8473-174417e027be
		summarizeBy: sum
		sourceColumn: Chickens_LSU

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ISO_Code
		dataType: string
		lineageTag: 9b59e8fb-b74b-42dc-a9bc-474f16b008e2
		summarizeBy: none
		sourceColumn: ISO_Code

		annotation SummarizationSetBy = Automatic

	partition countries = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\emily\Documents\whats_cooking\Bioenergy\livestock.csv"), [Delimiter = ",", Columns = 14, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Removed Other Columns" = Table.SelectColumns(#"Promoted headers",{"Area", "Area Code (M49)"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"Area"}),
				    #"Split Column by Position" = Table.SplitColumn(#"Removed Duplicates", "Area Code (M49)", Splitter.SplitTextByPositions({0, 3}, true), {"Area Code (M49).1", "Area Code (M49).2"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Position",{{"Area", type text}, {"Area Code (M49).1", type text}, {"Area Code (M49).2", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Area Code (M49).1"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Area Code (M49).2", "Area Code (M49)"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"Area Code (M49)"}, lsu_country, {"m49_code"}, "lsu_country", JoinKind.LeftOuter),
				    #"Expanded lsu_country" = Table.ExpandTableColumn(#"Merged Queries", "lsu_country", {"LSU_region_equivalent"}, {"lsu_country.LSU_region_equivalent"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded lsu_country", {"lsu_country.LSU_region_equivalent"}, LSU_region, {"Region"}, "LSU_region", JoinKind.LeftOuter),
				    #"Expanded LSU_region" = Table.ExpandTableColumn(#"Merged Queries1", "LSU_region", {"Cattle_LSU", "Sheep_LSU", "Goats_LSU", "Chickens_LSU"}, {"Cattle_LSU", "Sheep_LSU", "Goats_LSU", "Chickens_LSU"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded LSU_region",{{"lsu_country.LSU_region_equivalent", "LSU Region Equivalent"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1","Bolivia (Plurinational State of)","Bolivia",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Cabo Verde","Cape Verde",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Democratic Republic of the Congo","Democratic Republic of Congo",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Timor-Leste","East Timor",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Lao People's Democratic Republic","Laos",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Republic of Moldova","Moldova",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","Netherlands (Kingdom of the)","Netherlands",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","Democratic People's Republic of Korea","North Korea",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","Republic of Korea","South Korea",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","Russian Federation","Russia",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","Syrian Arab Republic","Syria",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","China, Taiwan Province of","Taiwan",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","United Republic of Tanzania","Tanzania",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","United Kingdom of Great Britain and Northern Ireland","United Kingdom",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","Venezuela (Bolivarian Republic of)","Venezuela",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","United States of America","United States",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","Côte d'Ivoire","Cote d'Ivoire",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value17" = Table.ReplaceValue(#"Replaced Value16","Iran (Islamic Republic of)","Iran",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17","Türkiye","Turkey",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value19" = Table.ReplaceValue(#"Replaced Value18","Viet Nam","Vietnam",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value20" = Table.ReplaceValue(#"Replaced Value19","Brunei Darussalam","Brunei",Replacer.ReplaceText,{"Area"}),
				    #"Replaced Value21" = Table.ReplaceValue(#"Replaced Value20","Congo","Congo (Republic of the)",Replacer.ReplaceValue,{"Area"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Replaced Value21", {"Area Code (M49)"}, ISO_Lookup, {"Area Code (M49)"}, "ISO_Lookup", JoinKind.LeftOuter),
				    #"Expanded ISO_Lookup" = Table.ExpandTableColumn(#"Merged Queries2", "ISO_Lookup", {"alpha-2", "alpha-3"}, {"alpha-2", "alpha-3"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Expanded ISO_Lookup",{"alpha-2"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns1",{{"alpha-3", "ISO_Code"}})
				in
				    #"Renamed Columns2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

