table manure
	lineageTag: 27b0647d-c1d2-4df1-9e4b-f79ebe9062a1

	column 'Domain Code'
		dataType: string
		lineageTag: 6b855d23-63ac-40d1-88c0-ab02bdd41b12
		summarizeBy: none
		sourceColumn: Domain Code

		annotation SummarizationSetBy = Automatic

	column Domain
		dataType: string
		lineageTag: 30e24283-a0a2-4ad4-8aa3-9995678b673b
		summarizeBy: none
		sourceColumn: Domain

		annotation SummarizationSetBy = Automatic

	column 'Area Code (M49)'
		dataType: int64
		formatString: 0
		lineageTag: 15052e13-7095-49bb-b955-81ebfa91230d
		summarizeBy: none
		sourceColumn: Area Code (M49)

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: d3a0277d-4868-4120-84a6-4a4f842f5ee1
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column 'Element Code'
		dataType: int64
		formatString: 0
		lineageTag: adc8fbcb-703a-4632-b3f4-dc23e26f4425
		summarizeBy: count
		sourceColumn: Element Code

		annotation SummarizationSetBy = Automatic

	column Element
		dataType: string
		lineageTag: c9e016f4-055d-40ef-976d-9c601ccb1c81
		summarizeBy: none
		sourceColumn: Element

		annotation SummarizationSetBy = Automatic

	column 'Item Code (CPC)'
		dataType: string
		lineageTag: 804b0da5-e288-4354-98fe-f95998fa5b7d
		summarizeBy: none
		sourceColumn: Item Code (CPC)

		annotation SummarizationSetBy = Automatic

	column Item
		dataType: string
		lineageTag: 9c26a26a-16f4-4dde-bceb-70c04323cf1b
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	column 'Year Code'
		dataType: int64
		formatString: 0
		lineageTag: f7ae7141-1ee9-43fe-ac9f-7455c71e6c98
		summarizeBy: count
		sourceColumn: Year Code

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 25f8428d-87b9-43b0-9e1a-fcafd7c91c13
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: d7a6ea69-4855-4ce4-86a6-b7ee284a477e
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 1ce94d0f-66c4-4356-9ec1-d6806417fc05
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Flag
		dataType: string
		lineageTag: 2214133f-df70-4700-9f48-9de4b5a113b6
		summarizeBy: none
		sourceColumn: Flag

		annotation SummarizationSetBy = Automatic

	column 'Flag Description'
		dataType: string
		lineageTag: 855a06dc-6036-4222-870e-980d99c13bfe
		summarizeBy: none
		sourceColumn: Flag Description

		annotation SummarizationSetBy = Automatic

	column Note
		dataType: string
		lineageTag: 1a6e7be6-1a83-49fe-850b-7ceacfed28cb
		summarizeBy: none
		sourceColumn: Note

		annotation SummarizationSetBy = Automatic

	column animal_type =
			
			SWITCH(
			    TRUE(),
			    'manure'[Item] IN { "Cattle, dairy", "Cattle, non-dairy" }, "Cattle",
			    'manure'[Item] IN { "Chickens, broilers", "Chickens, layers" }, "Chickens",
			    'manure'[Item] IN { "Goats", "Sheep" }, "Goats/Sheep",
			    'manure'[Item]
			)
		lineageTag: 279d24aa-7d8e-46a6-830d-12e297762931
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Daily_Manure_kg =
			
			SWITCH(
			    TRUE(),
			    manure[Item] = "Cattle, dairy",     28.0,  // Lower-bound for lactating cows (28–35 kg/day)
			    manure[Item] = "Cattle, non-dairy", 12.0,  // Lower-bound for beef/young stock (12–18 kg/day)
			    manure[Item] = "Chickens, broilers", 0.07,  // Small meat birds (~0.07 kg/day)
			    manure[Item] = "Chickens, layers",   0.10,  // Standard laying hens (~0.10 kg/day)
			    manure[Item] = "Goats",              1.20,  // Small ruminants / dry climates (~1.2 kg/day)
			    manure[Item] = "Sheep",              1.20,  // Small ruminants / dry climates (~1.2 kg/day)
			    BLANK()
			)
		lineageTag: 2dcffa44-fb77-4511-a77e-7471a6686635
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VS_Percentage =
			
			SWITCH(
			    TRUE(),
			    manure[item] = "Cattle, dairy",     0.82,  // ~82% of Total Solids (TS)
			    manure[item] = "Cattle, non-dairy", 0.80,  // ~80% of Total Solids (TS)
			    manure[item] = "Chickens, broilers", 0.75,  // ~75% of Total Solids (TS)
			    manure[item] = "Chickens, layers",   0.70,  // ~70% of Total Solids (TS)
			    manure[item] = "Goats",              0.80,  // ~80% of Total Solids (TS)
			    manure[item] = "Sheep",              0.80,  // ~80% of Total Solids (TS)
			    BLANK()
			)
		lineageTag: 996a2c13-4474-4cfc-a2f7-9b4a64ecc68e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TS_Percentage =
			
			SWITCH(
			    TRUE(),
			    manure[item] = "Cattle, dairy",     0.12,  // 12% Total Solids (88% moisture)
			    manure[item] = "Cattle, non-dairy", 0.14,  // 14% Total Solids (86% moisture)
			    manure[item] = "Chickens, broilers", 0.25,  // 25% Total Solids (dryer poultry litter)
			    manure[item] = "Chickens, layers",   0.22,  // 22% Total Solids
			    manure[item] = "Goats",              0.30,  // 30% Total Solids (drier, dense pellets)
			    manure[item] = "Sheep",              0.30,  // 30% Total Solids
			    BLANK()
			)
		lineageTag: a32a6a4e-76e6-4c31-b3a8-6dcf7b3075ac
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Biogas_Yield_m3_kg = ```
			
			VAR TS = manure[TS_Percentage]
			VAR VS = manure[VS_Percentage]
			VAR BiogasPerKgVS = 
			    SWITCH(
			        TRUE(),
			        manure[item] = "Cattle, dairy",     0.367,
			        manure[item] = "Cattle, non-dairy", 0.367,
			        manure[item] = "Chickens, broilers", 0.500,
			        manure[item] = "Chickens, layers",   0.500,
			        manure[item] = "Goats",              0.417,
			        manure[item] = "Sheep",              0.417,
			        BLANK()
			    )
			RETURN
			    TS * VS * BiogasPerKgVS
			```
		lineageTag: 58e82ffe-d5f6-48be-80fd-1a92e213ff0b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition manure = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\emily\Documents\whats_cooking\Bioenergy\manure.csv"), [Delimiter = ",", Columns = 15, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Domain Code", type text}, {"Domain", type text}, {"Area Code (M49)", Int64.Type}, {"Area", type text}, {"Element Code", Int64.Type}, {"Element", type text}, {"Item Code (CPC)", type text}, {"Item", type text}, {"Year Code", Int64.Type}, {"Year", Int64.Type}, {"Unit", type text}, {"Value", type number}, {"Flag", type text}, {"Flag Description", type text}, {"Note", type text}})
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

